name: 4 - Test Django with Actions Secret Database URL

on:
  workflow_dispatch:
  push:
    branch:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DEBUG: 0
      DATABASE_URL: ${{ secrets.NEON_DATABASE_URL }}
      EMAIL_HOST_USER: test@example.com
      EMAIL_HOST_PASSWORD: testpassword
      SECRET_KEY: dummy-secret-key-for-testing-only
      BASE_URL: http://localhost:8000
      ADMIN_USER_NAME: Test Admin
      ADMIN_USER_EMAIL: admin@example.com

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' 
      - name: Setup Django Secret Key
        run: |
          MY_GEN_KEY=$(openssl rand -base64 32)
          echo "DJANGO_SECRET_KEY=$MY_GEN_KEY" >> $GITHUB_ENV
      - name: Show DATABASE_URL
        run: |
          echo ${{ env.DATABASE_URL }}
          echo $DATABASE_URL
      - name: Install Requirements
        run: |
          python -m pip install pip --upgrade
          python -m pip install -r requirements.txt
      - name: Clean Test Database
        working-directory: ./src
        run: |
          python manage.py dbshell --noinput << EOF
          SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname = 'test_neondb';
          DROP DATABASE IF EXISTS test_neondb;
          EOF
        continue-on-error: true
      - name: Django Tests
        working-directory: ./src
        run: |
          python manage.py test --noinput